image: eclipse-temurin:17.0.1_12-jdk-focal

stages:
  - build
  - test

test-job:
  stage: test
  script:
    - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install -P integration-test

after_script:
  - bash <(curl -s https://codecov.io/bash) -f target/site/jacoco/jacoco.xml


