image: openjdk:17.0-slim

stages:
  - build
  - test

test-job:
  stage: test
  script:
    - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install

after_script:
  - bash <(curl -s https://codecov.io/bash)


