version: '3.1'

services:

  mysql:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Foodie
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
    volumes:
      - ./dockerdata:/var/lib/mysql


