spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/foodie?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 08e0e843a8251e
    password: 60e3d00f1c8e83
    protocol: smtp

okta:
  oauth2:
    scopes:
      - openid
      - profile
      - email
    audience: api://default
    groups-claim: roles

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false


    bucket.name: "talci-bucket"

cors:
  enabled: true

tomtom:
  api:
    url: "https://api.tomtom.com"

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
