spring:
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 08e0e843a8251e
    password: 60e3d00f1c8e83
    protocol: smtp

cloud:
  aws:
    bucket.name: "test-bucket"

tomtom:
  api:
    url: "https://api.tomtom.com"
    key: "testAPIKEY"

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
