spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/Foodie?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: spring
#    password: spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 08e0e843a8251e
    password: 60e3d00f1c8e83
    protocol: smtp
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false
    bucket.name: "test-bucket"

tomtom:
  api:
    url: "https://api.tomtom.com"
    key: "testAPIKEY"

