spring:
  datasource:
    url: jdbc:h2:mem:AZ
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
